services:
  db:
    image: postgres:15-alpine
    container_name: daraz_postgres
    restart: always
    environment:
      POSTGRES_USER: daraz_user
      POSTGRES_PASSWORD: daraz_password
      POSTGRES_DB: daraz_db
    ports:
      - "5432:5432"
    volumes:
      - daraz_pgdata:/var/lib/postgresql/data
      # Maps local database folder to docker postgres initialization directory.
      # Because "migrations.sql" starts with 'm' and "seed.sql" starts with 's',
      # migrations run before seed automatically inside the container.
      - ./database:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U daraz_user -d daraz_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - daraz_network

  backend:
    build: ./backend
    container_name: daraz_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_USER: daraz_user
      DB_PASSWORD: daraz_password
      DB_NAME: daraz_db
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - daraz_network

  frontend:
    build: ./frontend
    container_name: daraz_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SERVER_URL: http://backend:4000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - daraz_network

  nginx:
    image: nginx:alpine
    container_name: daraz_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./ngnix/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - daraz_network

volumes:
  daraz_pgdata:


networks:
  daraz_network:
    driver: bridge
